# Generated by Django 4.1.3 on 2022-11-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ok_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="images/profile/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="telegram_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="vkontakte_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="website_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
